config:
  internal_db: db_for_migrations
  target_db: my_project_db

databases:
  db_for_migrations:
    sqlite:
        database: 'monarch.sql'

  my_project_db:
    postgresql:
        dbname: 'mydb'
        user: 'postgresql'
        password: ''
        host: 'localhost'
        port: 5432
